### ISSUE TITLE
write_client.create_write_stream take too long time to respond

### ISSUE THREAD

**Issue by astrung** [googleapis/python-bigquery-storage#375]
#### Environment details

  - OS type and version: Windows10 64 bits, 
  - Python version: `python 3.6`
  - pip version: `pip 20.1.1`
  - `google-cloud-bigquery-storage` version: `2.10.1`

#### Steps to reproduce

After creating `bigquery_storage_v1.BigQueryWriteClient`, sometimes it takes too long time to create writing stream with method: `create_write_stream`, so i cancel it and it print below error. So how can i fix it ? is it an error from google server side and i have to wait, or i can do something to avoid it ?
This is my code: 

#### Code example

      credentials = service_account.Credentials.from_service_account_file('test.json')
      write_client = bigquery_storage_v1.BigQueryWriteClient(credentials=credentials)
      parent = write_client.table_path(project_id, dataset_id, table_id)
      write_stream = types.WriteStream()

      write_stream.type_ = types.WriteStream.Type.PENDING
      write_stream = write_client.create_write_stream(
          parent=parent, write_stream=write_stream
      )

#### Stack trace
```
  File "C:/Users/PycharmProjects/chatwork_ana/bigquery_stream.py", line 39, in append_rows_pending
    parent=parent, write_stream=write_stream
  File "C:\Users\anaconda3\envs\aimodule\lib\site-packages\google\cloud\bigquery_storage_v1\services\big_query_write\client.py", line 464, in create_write_stream
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "C:\Users\anaconda3\envs\aimodule\lib\site-packages\google\api_core\gapic_v1\method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\anaconda3\envs\aimodule\lib\site-packages\google\api_core\retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "C:\Users\anaconda3\envs\aimodule\lib\site-packages\google\api_core\retry.py", line 218, in retry_target
    time.sleep(sleep)
KeyboardInterrupt
```

Please help

#### Update:
I updated error happened when insteading of canceling it, i wait until it raises error (wating 5 mins):
```
Traceback (most recent call last):
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\google\api_core\grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1641876716.461000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3135,"referenced_errors":[{"created":"@1641876716.461000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\google\api_core\retry.py", line 190, in retry_target
    return target()
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\google\api_core\timeout.py", line 99, in func_with_timeout
    return func(*args, **kwargs)
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\google\api_core\grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/hblab-user1/PycharmProjects/chatwork_ana/bigquery_stream.py", line 123, in <module>
    append_rows_pending('nlp-329509', 'anhnt5_test', 'test')
  File "C:/Users/hblab-user1/PycharmProjects/chatwork_ana/bigquery_stream.py", line 42, in append_rows_pending
    parent=parent, write_stream=write_stream, timeout=10
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\google\cloud\bigquery_storage_v1\services\big_query_write\client.py", line 464, in create_write_stream
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\google\api_core\gapic_v1\method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\google\api_core\retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "C:\Users\hblab-user1\anaconda3\envs\aimodule\lib\site-packages\google\api_core\retry.py", line 210, in retry_target
    ) from last_exc
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses
```

**Comment by tswast** [comment]
Generally, this occurs when there is a server-side issue. When this happens the best bet is to try again and hope you connect to a different server.

I'll mark this as a bug for now to see if there's anything we can do client-side to detect this situation.

**Comment by astrung** [comment]
well, i reinstall my windows 10 and everything is fine. I tried to reinstall anaconda, gcloud, ssl certification on windows but nothing works. It looks like somethings has hidden conflicts in my computer.

**Comment by shollyman** [comment]
The error here seems to be indicative of a bad transport channel, but there's nothing really actionable here for the client library other than recommending use of a timeout value.  There's not really enough information to disambiguate the cause of the transport problem.

See the [library reference](https://cloud.google.com/python/docs/reference/bigquerystorage/latest/google.cloud.bigquery_storage_v1.services.big_query_write.BigQueryWriteClient#google_cloud_bigquery_storage_v1_services_big_query_write_BigQueryWriteClient_create_write_stream) for args to create_write_stream.
